#ifndef __HOME_DAN_HALL_DEV_SRC_CSTDLIB_SRC_GC_UTILITY_H_
#define __HOME_DAN_HALL_DEV_SRC_CSTDLIB_SRC_GC_UTILITY_H_

#include "gc_utility.h"

#endif /* __HOME_DAN_HALL_DEV_SRC_CSTDLIB_SRC_GC_UTILITY_H_ */
